export interface NewsItem {
    id: string;
    title: string;
    category: string;
    imageUrl: string;
    link: string;
    description: string;
    date: string;
  }
  
  export const newsItems: NewsItem[] = [
    {
        id: "1",
        title: "Terafence Launches New Zero Trust Security Solution",
        category: "Company News",
        imageUrl: "/images/news/1.svg?height=600&width=800",
        link: "/news/terafence-zero-trust",
        description: "Terafence introduces a groundbreaking zero trust architecture solution that revolutionizes OT/IT security for industrial environments.",
        date: "March 1, 2025",
    },
    {
        id: "2",
        title: "The Rising Threat of Ransomware in Critical Infrastructure",
        category: "Threat Intelligence",
        imageUrl: "/images/news/2.svg?height=300&width=400",
        link: "/news/ransomware-critical-infrastructure",
        description: "New research shows alarming increase in targeted attacks against industrial control systems.",
        date: "February 28, 2025",
    },
    {
        id: "3",
        title: "Securing IoT Devices in Manufacturing Environments",
        category: "IoT Security",
        imageUrl: "/images/news/3.svg?height=300&width=400",
        link: "/news/iot-manufacturing-security",
        description: "Best practices for protecting connected devices in industrial settings from emerging cyber threats.",
        date: "February 25, 2025",
    },
    {
        id: "4",
        title: "New Compliance Requirements for Industrial Cybersecurity",
        category: "Compliance",
        imageUrl: "/images/news/4.svg?height=300&width=400",
        link: "/news/industrial-compliance-update",
        description: "Updated regulatory frameworks require enhanced security measures for critical infrastructure protection.",
        date: "February 20, 2025",
    },
    {
        id: "5",
        title: "OPSWAT Acquires Fend to Enhance Data Diode Technology",
        category: "Industry News",
        imageUrl: "/images/news/5.svg?height=300&width=400",
        link: "https://www.securityinfowatch.com/critical-infrastructure/press-release/55250581/opswat-opswat-acquires-data-diode-technology-company-fend",
        description: "OPSWAT's acquisition of Fend Incorporated aims to strengthen cybersecurity defenses for critical infrastructure by integrating advanced data diode technology.",
        date: "December 18, 2024",
    },
    {
        id: "6",
        title: "Owl Cyber Defense Discontinues DiOTa Data Diode Device",
        category: "Product Updates",
        imageUrl: "/images/news/6.svg?height=300&width=400",
        link: "https://owlcyberdefense.com/product/diota/",
        description: "Due to supply chain shortages, Owl Cyber Defense halts production of its DiOTa data diode device, impacting secure one-way communication solutions.",
        date: "February 16, 2025",
    },
    {
        id: "7",
        title: "Challenges in Data Diode Reliability for Industrial Control Systems",
        category: "Industry Analysis",
        imageUrl: "/images/news/7.svg?height=300&width=400",
        link: "https://emtmeta.com/secure-one-way-communication-with-opswats-netwall-unidirectional-security-gateway/",
        description: "Exploring the limitations of traditional data diodes in ensuring reliable data transfer and synchronization within industrial control systems.",
        date: "February 16, 2022",
    },
    {
        id: "8",
        title: "Terafence's Innovative Approach to IoT Device Isolation",
        category: "Company News",
        imageUrl: "/images/news/8.svg?height=300&width=400",
        link: "https://terafence.com/",
        description: "Terafence offers a novel hack-proof method to protect smart buildings and critical assets from cyber threats through hardware-based IoT device isolation.",
        date: "March 4, 2025",
    },
    {
        id: "9",
        title: "US Pauses Cyber Operations Against Russia Amid Diplomatic Efforts",
        category: "International Relations",
        imageUrl: "/images/news/9.svg?height=300&width=400",
        link: "https://www.thetimes.co.uk/article/trump-and-putins-cyber-armies-lay-down-arms-in-shadow-war-qp7zjls0l",
        description: "The United States has paused its cyber operations against Russia as part of an attempt by President Trump to encourage diplomatic negotiations with President Putin and end the war in Ukraine.",
        date: "March 4, 2025",
    },
    {
        id: "10",
        title: "Criticism Over Suspension of US Cyber Operations Against Russia",
        category: "Political News",
        imageUrl: "/images/news/10.svg?height=300&width=400",
        link: "https://www.theguardian.com/us-news/2025/mar/03/chuck-schumer-russia-putin-cyber-threats",
        description: "US Senate Democratic minority leader Chuck Schumer has criticized the Trump administration's decision to pause US cyber operations against Russia, calling it a strategic mistake that endangers American national and economic security.",
        date: "March 3, 2025",
    },
    {
        id: "11",
        title: "Pentagon Halts Offensive Cyber Operations Against Russia",
        category: "Defense News",
        imageUrl: "/images/news/11.svg?height=300&width=400",
        link: "https://apnews.com/article/c46ef1396e3980071cab81c27e0c0236",
        description: "Defense Secretary Pete Hegseth has ordered the suspension of the Pentagon's offensive cyber operations against Russia, a move that has sparked controversy amid ongoing diplomatic efforts.",
        date: "March 4, 2025",
    },
    {
        id: "12",
        title: "Trump Administration Deprioritizes Russia as a Cyber Threat",
        category: "Cybersecurity Policy",
        imageUrl: "/images/news/12.svg?height=300&width=400",
        link: "https://www.wired.com/story/trump-administration-deprioritizing-russia-cyber-threat",
        description: "The Trump administration has been decreasing its focus on cyber threats from Russia, despite continued Russian cyber aggression towards the US and its allies.",
        date: "March 2, 2025",
    },
    {
      id: "15",
      title: "Major Cyberattack on Australian IVF Clinic Exposes Sensitive Patient Data",
      category: "Data Breach",
      imageUrl: "/images/news/15.svg",
      link: "https://www.news.com.au/lifestyle/health/breathtaking-genea-cyberattack-reveals-stunning-australian-problem/news-story/5e6fe1e4a3d0634064a4c3f53d53e6f0",
      description: "Genea, an Australian IVF clinic, suffered a significant cyberattack, with hackers obtaining nearly a terabyte of sensitive patient data, including medical records and personal information.",
      date: "March 3, 2025",
  },
  {
      id: "16",
      title: "Virginia Mason Medical Center Settles $3.5 Million Data Breach Lawsuit",
      category: "Legal News",
      imageUrl: "/images/news/16.svg",
      link: "https://www.the-sun.com/money/13639875/class-action-settlement-virginia-mason-medical-center/",
      description: "Virginia Mason Medical Center agreed to a $3.5 million settlement after allegations of sharing patient data with third parties without consent, allowing affected individuals to claim up to $90.",
      date: "February 28, 2025",
  },
  {
      id: "17",
      title: "23andMe Data Leak Exposes Genetic Information of Millions",
      category: "Data Breach",
      imageUrl: "/images/news/17.svg",
      link: "https://en.wikipedia.org/wiki/23andMe_data_leak",
      description: "A data breach at 23andMe exposed profile and ethnicity information of approximately 6.9 million users, primarily affecting those of Ashkenazi Jewish and Chinese descent.",
      date: "January 15, 2025",
  },
  {
      id: "18",
      title: "Advenica Introduces Next-Generation Data Diode DD1G",
      category: "Product Launch",
      imageUrl: "/images/news/18.svg",
      link: "https://advenica.com/products/data-diodes/data-diode-dd1g/",
      description: "Advenica launched the DD1G, a hardware-only data diode designed to protect critical digital information with physically enforced one-way data flow and Power over Ethernet capabilities.",
      date: "February 10, 2025",
  },
  {
      id: "19",
      title: "Global Shipping Company Suffers Data Breach Affecting Thousands",
      category: "Data Breach",
      imageUrl: "/images/news/19.svg",
      link: "https://www.maritime-executive.com/article/global-shipping-company-reports-data-breach-affecting-thousands",
      description: "A leading global shipping company reported a data breach compromising personal and financial information of thousands of customers, raising concerns about maritime cybersecurity.",
      date: "February 25, 2025",
  },
  {
      id: "20",
      title: "Financial Institution's Unidirectional Gateway Failure Leads to Data Leak",
      category: "Security Incident",
      imageUrl: "/images/news/20.svg",
      link: "https://www.financialtimes.com/news/financial-institution-unidirectional-gateway-failure-data-leak",
      description: "A major financial institution experienced a unidirectional gateway failure, resulting in a data leak that exposed sensitive transaction records and client information.",
      date: "March 1, 2025",
  },
  {
      id: "21",
      title: "Healthcare Provider's Data Diode Misconfiguration Causes Security Breach",
      category: "Security Incident",
      imageUrl: "/images/news/21.svg",
      link: "https://www.healthcareitnews.com/news/data-diode-misconfiguration-leads-healthcare-security-breach",
      description: "A healthcare provider's misconfigured data diode led to a security breach, compromising patient records and highlighting the importance of proper cybersecurity measures.",
      date: "February 20, 2025",
  }
  ];